s/\\PYGZhy{}\\PYGZgt{}/->/g
s/\\PYGZti{}\\PYGZgt{}/~>/g
s/\\PYGZlt{}=\\PYGZgt{}/<=>/g
s/\\PYGZlt{}\\PYGZhy{}/<-/g
s/\\PYGZgt{}\\PYGZgt{}=/>>=/g
s/\\PYGZlt{}|\\PYGZgt{}/<|>/g
s/\\PYG{n}{extern}/\\PYG{k+kn}{extern}/g
s/\\PYG{n\+nv}{defforeign}/\\PYG{n+nb}{defforeign}/g
s/\\PYG{n}{partial}/\\PYG{k+kn}{partial}/g
s/\\PYG{n}{mutual}/\\PYG{k}{mutual}/g
s/\\PYG{n+nf}{and}/\\PYG{k+kr}{and}/g
s/\\PYG{n}{and}/\\PYG{k+kr}{and}/g